name: Development(Server)

on: 
  push:
    paths:
      - 'packages/server/**'
      - '.github/workflows/server-development.yml'
    branches-ignore:
      - master
      
jobs:
  container-job:
    name: Test
    runs-on: ubuntu-latest
    container: node:12

    services:
      postgres:
        image: postgres:12.2
        env:
          POSTGRES_USER: typeorm
          POSTGRES_PASSWORD: password
          POSTGRES_DB: todo-test
        ports: 
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.0.0'
      - run: yarn install
      - run: yarn lint:server
      - run: yarn test:server
