name: Development(Server)

on: 
  push:
    paths:
      - 'packages/server/**'
      - '.github/workflows/server-development.yml'
    branches-ignore:
      - master
      
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.0.0'
      - uses: huaxk/postgis-action@v1
        with:
          postgresql version: '11'
          postgresql db: todo-test
          postgresql user: typeorm
          postgresql password: password
      - run: yarn install
      - run: yarn lint:server
      - run: yarn test:server
